back-end/PHP/laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace'=>'Home'],function(){

    Route::group([],function (){
        //前台首页路由
        Route::get('/', 'IndexController@index')->name('index');
        //文章详情页
        Route::get('/article/{id}', 'ArticleController@index')->where('id','\d+');
        //说说页面
        Route::get('/chat','ChatController@index');
        //分类文章页面
        Route::get('/category/{id}','CategoryController@index')->where('id','\d+');
        //标签文章页面
        Route::get('/tag/{id}','TagController@index')->where('id','\d+');
        //搜索文章
        Route::get('/search','ArticleController@search');
        //添加友联
        Route::post('/link','LinkController@store');
        //联系我页面
        Route::get('/contact','ContactController@index');
        //添加留言
        Route::post('/contact','ContactController@store');
        //添加评论
        Route::post('/comment','CommentController@store');
        //退出登录
        Route::get('/logout','OauthController@logout');
    });

    //微信组
    Route::group(['prefix'=>'wechat'],function (){
        //前台首页路由
        Route::get('/', 'IndexController@index');
        //获取小程序scene
        Route::get('/scene', 'WeChatController@getScene');
        //获取小程序码
        Route::get('/qrcode/{scene}', 'WeChatController@getQrCode');
        //获取微信登录状态
        Route::get('/status', 'WeChatController@getLoginResult');
    });

    //微信小程序登录
    Route::post('/home/wechat', 'WeChatController@login');

    //三方登录组
    Route::group(['prefix'=>'oauth'],function (){
        //三方用户授权
        Route::get('/redirectToProvider/{service}','OauthController@oauth');
        //处理授权回调
        Route::get('/handleOauth/{service}','OauthController@callback');
    });

});

back-end/PHP/laravel/app/Http/Controllers/Home/ArticleController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Models\Article;
use App\Http\Models\ArticleComment;
use Illuminate\Http\Request;

class ArticleController extends BasicController
{
    /**
     * 文章详情页
     * Date: 2019/1/16 10:53
     * @param Request $request
     * @param         $id
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, $id)
    {
        //得到单一文章详情
        $single = Article::with('tags:tag.id,name', 'category:category.id,category.title')
            ->withCount('comments')
            ->findorfail($id);
        //文章查看次数,一个用户一天只增加一次
        $view = $this->countView($request);
        $prev = $this->getPreArticle($id);
        $next = $this->getNextArticle($id);
        $randArticle = $this->getRandomArticle();
        $comment = $this->handleCommentData($id);
        return response()->view('home.single', compact('single', 'randArticle', 'prev',
            'next','comment'))->cookie('view_article', $view, 1440);
    }

    /**
     * 获取上一篇文章
     * Date: 2019/1/11 15:49
     * @param int $id
     * @return mixed
     */
    private function getPreArticle(int $id)
    {
        return Article::where('id', '<', $id)
            ->show(1)
            ->latest('id')
            ->select('id', 'title')
            ->first();
    }

    /**
     * 获取下一篇文章
     * Date: 2019/1/11 15:50
     * @param int $id
     * @return mixed
     */
    private function getNextArticle(int $id)
    {
        return Article::where('id', '>', $id)
            ->show(1)
            ->oldest('id')
            ->select('id', 'title')
            ->first();
    }

    /**
     * 获取随机文章
     * Date: 2019/1/11 15:51
     * @return mixed
     */
    private function getRandomArticle()
    {
        return Article::inRandomOrder()
            ->show(1)
            ->take(10)
            ->select('title', 'thumb', 'id')
            ->get();
    }

    /**
     * 获取评论数据
     * Date: 2019/1/11 15:48
     * @param int $article_id
     * @return mixed
     */
    private function handleCommentData(int $article_id)
    {
        $where = [
            ['article_comment.article_id',$article_id],
            ['article_comment.pid',0]
        ];
        $query = ArticleComment::with(['children' => function ($q) {
            return $this->buildQuery($q);
        }]);
        $comment = $this->buildQuery($query)
            ->where($where)
            ->get();
        return $comment;
    }

    /**
     * 构造查询
     * Date: 2019/1/10 14:57
     * @param $q
     * @return mixed
     */
    private function buildQuery($q)
    {
        return $q->leftJoin('user as a', 'article_comment.reply_id', '=', 'a.id')
            ->leftJoin('user as b', 'article_comment.user_id', '=', 'b.id')
            ->select('article_comment.*', 'a.avatar as reply_avatar',
                'a.name as reply_name', 'b.avatar as user_avatar', 'b.name as username');
    }

    /**
     * 搜索文章
     * Date: 2019/1/16 10:57
     * @param Request $request
     * @param Article $article
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function search(Request $request,Article $article)
    {
        $search = $request->input('search',null);
        $list = $article->with('tags:tag.id,name', 'category:category.id,category.title')
            ->when($search,function ($q) use ($search){
            return $q->where('title', 'like', '%' . $search . '%');
        })->latest()->paginate(7);
        return view('home.category', compact('list'));
    }
}

back-end/PHP/laravel/app/Http/Controllers/Home/BasicController.php
<?php
/**
 * Created by huxin.
 * User: huxin
 * Date: 2019/1/8
 * Time: 15:54
 */

namespace App\Http\Controllers\Home;


use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cache;

class BasicController extends Controller
{

    //统计页面访问次数
    public function countView($request)
    {
        $ip = getIP();
        $time = time();
        $page_name = $request->route()->getName();
        if ($page_name == 'index')
        {
            $key = config('blog.blog_index_count_key');
            $view_cookie = $request->cookie('view_index', '');
            if (!empty($view_cookie))
            {
                list($rtime, $rip) = explode('#', $view_cookie);
                if ($this->calculateTimeDiff($rtime, $time) >= 1)
                {
                    $this->handleCacheData($key);
                }
            } else
            {
                $this->handleCacheData($key);
            }
            $view_cookie = $time . '#' . $ip;
        } else
        {
            $view_cookie = $request->cookie('view_article', '');
            $id = $request->route()->parameter('id');
            $key = config('blog.blog_article_count_key');
            if (!empty($view_cookie))
            {
                list($rtime, $aid) = explode('#', $view_cookie);
                $aid = explode(',', $aid);
                if ($this->calculateTimeDiff($rtime, $time) >= 1 || !in_array($id, $aid))
                {
                    $this->handleCacheData($key);
                }
                $aid[] = $id;
                $aid = array_unique($aid);
                $view_cookie = $time . '#' . implode(',', $aid);
            } else
            {
                $view_cookie = $time . '#' . $id;
                $this->handleCacheData($key);
            }
        }
        return $view_cookie;
    }

    //计算时间
    private function calculateTimeDiff($start, $end)
    {
        return floor(($end - $start) / 86400);
    }

    //处理缓存
    private function handleCacheData($key)
    {
        if(Cache::has($key)){
            Cache::increment($key);
        }else{
            $val = db('web_config')
                ->where('name','blog_view_count')
                ->value('val');
            Cache::put($key,$val,86400);
        }
    }

}

back-end/PHP/laravel/app/Http/Controllers/Home/CategoryController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Models\Article;

class CategoryController extends BasicController
{
    /**
     * 分类文章页面
     * Date: 2019/1/15 14:51
     * @param         $id
     * @param Article $article
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index($id,Article $article)
    {
        $list = $article->with('tags:tag.id,name', 'category:category.id,category.title')
            ->where('category_id', $id)
            ->latest()
            ->paginate(7);
        return $list->isNotEmpty()?view('home.category', compact('list'))
            :view('home.kong');
    }
}

back-end/PHP/laravel/app/Http/Controllers/Home/ChatController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Models\Chat;

class ChatController extends BasicController
{
    /**
     * 说说页面
     * Date: 2019/1/15 14:13
     * @param Chat $chat
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Chat $chat)
    {
        $data = $chat->latest()->show(1)->get();
        return view('home.chat', compact('data'));
    }
}

back-end/PHP/laravel/app/Http/Controllers/Home/CommentController.php
<?php

namespace App\Http\Controllers\Home;

use App\Events\NotifyUserEvent;
use App\Http\Controllers\Controller;
use App\Http\Models\ArticleComment;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CommentController extends Controller
{
    /**
     * 评论
     * Date: 2019-01-29 11:46
     * @param Request $request
     * @return JsonResponse
     * @throws \Illuminate\Validation\ValidationException
     * @throws \Throwable
     */
    public function store(Request $request, ArticleComment $articleComment): JsonResponse
    {
        $data = $this->validate($request, [
            'email'      => 'required|email',
            'content'    => 'required|min:2',
            'user_id'    => 'required|integer|min:1',
            'reply_id'   => 'nullable|integer|min:0',
            'article_id' => 'required|integer|min:1',
            'pid'        => 'nullable|integer|min:0'
        ]);
        try
        {
            DB::transaction(function () use ($data, $articleComment) {
                $email = $data['email'];
                $data['created_at'] = time();
                $data['updated_at'] = time();
                unset($data['email']);
                \db('article_comment')->insert($data);
                \db('user')->where('id', $data['user_id'])->update(['email' => $email]);
                session(['user.email' => $email]);
                $this->sendCommentEmail($data, $email);
                $articleComment->flushCache();
            });
            return renderSuccess('评论成功！');
        } catch (\Exception $e)
        {
            return renderError('评论失败，请稍后再试！');
        }
    }

    /**
     * 发送邮件通知
     * Date: 2019-01-29 13:33
     * @param array  $data
     * @param string $email
     */
    private function sendCommentEmail(array $data, string $email): void
    {
        event(new NotifyUserEvent($data, $email));
    }
}

back-end/PHP/laravel/app/Http/Controllers/Home/ContactController.php
<?php
/**
 * Created by huxin.
 * User: huxin
 * Date: 2019-01-28
 * Time: 14:56
 */

namespace App\Http\Controllers\Home;


use App\Http\Models\Contact;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class ContactController extends BasicController
{
    /**
     * 联系我
     * Date: 2019-01-28 15:04
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('home.contact');
    }

    /**
     * 留言
     * Date: 2019-01-29 10:35
     * @param Request $request
     * @param Contact $contact
     * @return JsonResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request,Contact $contact): JsonResponse
    {
        $data = $this->validate($request, [
            'name' => 'required|between:2,20',
            'email' => 'required|email',
            'content' => 'required|between:2,255'
        ], [
            'name.required' => '请输入姓名！',
            'name.between' => '姓名在2到20个字符之间！',
            'email.required' => '请输入邮箱',
            'email.email' => '请输入正确的邮箱',
            'content.required' => '请输入留言内容！',
            'content.between' => '留言内容在2到255个字符之间！'
        ]);
        $contact->name = $data['name'];
        $contact->email = $data['email'];
        $contact->content = $data['content'];
        $res = $contact->save();
        return $res?renderSuccess('留言成功！'):renderError('留言失败，请稍后再试！');
    }
}

back-end/PHP/laravel/app/Http/Controllers/Home/LinkController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Models\Link;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LinkController extends Controller
{
    /**
     * 申请友联
     * Date: 2019/1/16 13:18
     * @param Request $request
     * @param Link    $link
     * @return JsonResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request,Link $link): JsonResponse
    {
        $data = $this->validate($request, [
            'name' => 'required|between:2,50',
            'url' => 'required|url',
            'description' => 'required|between:2,50'], [
            'name.required' => '请输入友联名称',
            'name.between' => '友联名称在2到50个字符之间',
            'url.required' => '请输入友联地址',
            'url.url' => '友联地址不正确',
            'description.required' => '请输入友联描述',
            'description.between' => '友联描述在2到50个字符之间'
        ]);
        $res = $link->create($data);
        return $res?renderSuccess('申请友联成功!')
            :renderError('申请友联失败,请稍后再试!');
    }
}

back-end/PHP/laravel/app/Http/Controllers/Home/OauthController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Models\User;
use Illuminate\Http\Request;

class OauthController extends BasicController
{
    /**
     * 三方登录授权
     * Date: 2019/1/16 16:01
     * @param $service
     * @return mixed
     */
    public function oauth(Request $request,$service)
    {
        $http_referer = \request()->server('HTTP_REFERER');
        $target_url = $http_referer ? $http_referer : config('blog.blog_home');
        session(['target_url' => $target_url]);
        return app('socialite')->setRequest($request)->driver($service)->redirect();
    }

    /**
     * 授权回调
     * Date: 2019/1/16 16:10
     * @param Request $request
     * @param         $service
     * @param User    $user
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function callback(Request $request, $service, User $user)
    {
        $type = [
            'weibo' => 3,
            'wechat' => 2,
            'qq' => 1
        ];
        $oauth_user = app('socialite')->setRequest($request)->driver($service)->user();
        $data = [
            'openid' => $oauth_user->getId(),
            'type' => $type[$service],
        ];
        $exist_user = $user->firstOrNew($data);
        $exist_user->access_token = $oauth_user->getAccessToken();
        $exist_user->name = $oauth_user->getName();
        $exist_user->last_login_ip = $request->getClientIp();
        $exist_user->login_times = isset($exist_user->login_times) ? $exist_user->login_times + 1 : 1;
        $exist_user->avatar = str_replace('http', 'https', $oauth_user->getAvatar());
        $exist_user->save();
        $sessionData = [
            'user' => [
                'id' => $exist_user->id,
                'name' => $oauth_user->getName(),
                'is_admin' => $exist_user->is_admin,
                'email' => $exist_user->email ?? null
            ]
        ];
        session($sessionData);
        auth('web')->loginUsingId($exist_user->id);
        return redirect(session('target_url', url('/')));
    }

    /**
     * 退出登录
     * Date: 2019/1/16 16:11
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function logout(Request $request)
    {
        auth('web')->logout();
        $request->session()->forget('user');
        return renderSuccess('退出成功！');
    }
}

back-end/PHP/laravel/app/Http/Controllers/Home/TagController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Models\Article;
use App\Http\Models\Tag;

class TagController extends BasicController
{
    /**
     * 标签相关文章
     * Date: 2019/1/16 10:51
     * @param         $id
     * @param Tag     $tag
     * @param Article $article
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index($id,Tag $tag,Article $article)
    {
        //获取标签名字
        $tag_name = $tag->where('id', $id)->value('name');
        //获取拥有该标签的文章id
        $list = $article->with('tags:tag.id,name', 'category:category.id,category.title')
            ->whereHas('tags',function ($q) use ($id){
            return $q->where('tag.id',$id);
        })->latest()->paginate(7);
        return view('home.category', compact('list', 'tag_name'));
    }
}

back-end/PHP/laravel/resources/views/home/chat.blade.php
@extends('home.layouts.home')

@section('content')
@section('main-content')
    <div id="main-content" class="col-md-8">
        <div id="b-content" class="container">
            <div class="row">
                @if($data->isNotEmpty())
                    <div class="col-xs-12 col-md-12 col-lg-8 b-chat">
                        <div class="b-chat-left">
                            @foreach($data as $k => $v)
                                @if($k%2 == 0)
                                    <ul class="b-chat-one animated bounceInLeft">
                                        <li class="b-chat-title ">{{$v->created_at}}</li>
                                        <li class="b-chat-content">{{$v->content}}</li>
                                        <div class="b-arrows-right1">
                                            <div class="b-arrows-round"></div>
                                        </div>
                                        <div class="b-arrows-right2"></div>
                                    </ul>
                                @endif
                            @endforeach
                        </div>
                        <div class="b-chat-middle"></div>
                        <div class="b-chat-right">
                            @foreach($data as $k => $v)
                                @if($k%2 == 1)
                                    <ul class="b-chat-one animated bounceInRight">
                                        <li class="b-chat-title ">{{$v->created_at}}</li>
                                        <li class="b-chat-content">{{$v->content}}</li>
                                        <div class="b-arrows-right1">
                                            <div class="b-arrows-round"></div>
                                        </div>
                                        <div class="b-arrows-right2"></div>
                                    </ul>
                                @endif
                            @endforeach
                        </div>
                    </div>
                @else
                    暂无说说数据
                @endif
            </div>
        </div>
    </div>
@endsection
<script src="{{asset('js/index.js')}}" type="text/javascript"></script>

@endsection

back-end/PHP/laravel/resources/views/home/single.blade.php
@php
    $agent = new \Jenssegers\Agent\Agent();
@endphp
@extends('home.layouts.home')
@section('meta')
    <title>{{config('webConfig.web_title')}}-{{$single->title ?? ''}}</title>
    <meta name="keywords" content="{{$single->keywords ?? ''}}">
    <meta name="description" content="{{$single->description ?? ''}}">
    @stop
@push('other-css')
    <style>
        code {
            padding: 2px 4px;
            font-size: 90%;
            color: #c7254e;
            background-color: #f9f2f4;
            border-radius: 4px;
            white-space:unset;
        }
    </style>
    @endpush
@section('content')
    <body>
    <div class="featured container">
        <h7>随机文章推荐</h7>
        <br/>
        <div id="owl-demo-2" class="owl-carousel">
            @foreach($randArticle as $ra)
                <div class="item">
                    <div class="zoom-container">
                        <div class="zoom-caption" title="{{$ra->title}}">
                            <span></span>
                            <a href="{{url('article/'.$ra->id)}}">
                                <i class="" style="color: #fff"></i>
                            </a>
                        </div>
                        <img src="{{$ra->thumb}}" style="width: 200px;height: 128px" title="{{$ra->title}}"/>
                    </div>
                </div>
            @endforeach
        </div>

    </div>
    <!-- Header -->
    @section('main-content')
        <div id="main-content" class="col-md-8">
            <div class="box single_article">
                <div class="line"></div>
                <h2 style="text-align: center;color: black;" title="{{$single->title}}">{{$single->title}}</h2>
                <div class="info">
                        <span class="center1"><i class="fa fa-user"></i>{{$single->author}}</span>
                        <span class="center1"><i class="fa fa-calendar"></i>{{$single->created_at}}</span>
                        <span class="center1"><i class="fa fa-eye"></i>{{$single->click}}</span>
                    @if($agent->isDesktop() || $agent->is('Windows'))
                    <span class="center1"><i class="fa fa-comments-o"></i>{{$single->comments_count}}&nbsp;comments</span>
                    @endif
                </div>
                <p style="margin-top: 20px;">{!! $single->content_html !!}</p>
                <br/>
                <ul class="b-prev-next">
                    <li class="b-prev">
                        上一篇：
                        @if(is_null($prev))
                            <span>没有了</span>
                        @else
                            <a href="{{ url('article/'.$prev->id) }}"
                               style="color: black">{{ $prev->title }}</a>
                        @endif

                    </li>
                    <li class="b-next">
                        下一篇：
                        @if(is_null($next))
                            <span>没有了</span>
                        @else
                            <a href="{{ url('article/'.$next->id) }}"
                               style="color: black">{{ $next->title }}</a>
                        @endif
                    </li>
                </ul>
                <div class="share">
                    <div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more">
                        </a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                        <a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                        <a href="#" class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a>
                        <a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a>
                        <a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
                        <a href="#" class="bds_twi" data-cmd="twi" title="分享到Twitter"></a>
                    </div>
                    <script>window._bd_share_config = {
                            "common": {
                                "bdSnsKey": {},
                                "bdText": "",
                                "bdMini": "2",
                                "bdMiniList": false,
                                "bdPic": "",
                                "bdStyle": "1",
                                "bdSize": "24"
                            }, "share": {}
                        };
                        with (document) 0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = '{{asset("static/api/js/share.js")}}?v=89860593.js?'];</script>
                </div>
                <br/>
                <h6>标签</h6>
                <div class="vid-tags">
                    @foreach($single->tags as $tag)
                        <a href="{{url('tag/'.$tag->id)}}">{{$tag->name}}</a>
                    @endforeach
                </div>
                <div class="line"></div>
                <div class="comment a_comment">
                    <h5>评论一下</h5>
                    <div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="email" class="form-control input-lg" name="email" id="email"
                                           placeholder="接收回复的邮箱" required="required" value="{{session('user.email') ?? ''}}"/>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <textarea name="message" id="message" class="form-control" rows="4" cols="25"
                                              required="required" placeholder="评论内容"></textarea>
                                </div>
                                <button type="submit" class="btn btn-4 btn-block save" data="{{$single->id ?? ''}}" style="background-color: #f0efee">
                                    立即评论
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <br/>
                <h5>评论列表</h5>
                <hr/>
                <div class="widget wid-comment hx-comments">
                    <div class="content">
                        @if($comment->isNotEmpty())
                            @foreach($comment as $com)
                                <div class="post">
                                    <img src="{{$com->user_avatar}}" class="img-circle" title="{{$com->username}}"/>
                                    <div class="wrapper" style="max-width: 620px;display: inline-block;text-align: left;margin-left: 5px">
                                        <ul class="list-inline">
                                            <li>{{$com->username}}&emsp;评论:</li>
                                        </ul>
                                        <h5>{{$com->content ?? ''}}</h5>
                                        <ul class="list-inline">
                                            <li><i class="fa fa-calendar"></i> {{$com->created_at ?? ''}}</li>
                                            <li style="cursor: pointer" class="c_reply"><i class="fa fa-comment"></i>回复</li>
                                        </ul>
                                    </div>
                                    <div class="form-group hx_group" style="display: none">
                                        <textarea id="co_content" name="co_content" class="form-control co_content" required="required" placeholder="回复内容"></textarea>
                                        <input class="pull-left co_email" type="email" name="co_email" placeholder="请输入接收回复的邮箱" required="required" value="{{session('user.email') ?? ''}}"/>
                                        <button type="submit" class="btn btn-success co_reply" data-pid="{{$com->id ?? ''}}" data-aid="{{$single->id ?? ''}}" data-rid="{{$com->user_id ?? ''}}">回复</button>
                                        <button type="submit" class="btn btn-success co_cancel">取消</button>
                                    </div>
                                    @if($com->children->isNotEmpty())
                                        @foreach($com->children as $childComment)
                                            <div class="post hx_child_comments" style="margin-left: 55px;margin-bottom: 0; border-bottom: 1px solid #ddd;padding-top: 10px;">
                                                <img src="{{asset($childComment->user_avatar)}}" class="img-circle" title="{{$childComment->username}}"/>
                                                <div class="wrapper child_wrapper" style="max-width: 580px;display: inline-block;text-align: left;margin-left: 5px">
                                                    <ul class="list-inline">
                                                        <li>{{$childComment->username}}&nbsp;回复&nbsp;{{$childComment->reply_name}}</li>
                                                    </ul>
                                                    <h5>{{$childComment->content}}</h5>
                                                    <ul class="list-inline">
                                                        <li><i class="fa fa-calendar"></i>{{$childComment->created_at}}</li>
                                                        <li style="cursor: pointer" class="hx_child_co_reply"><i class="fa fa-comments"></i>回复</li>
                                                    </ul>
                                                </div>
                                                <div class="form-group hx_child_group" style="display: none">
                                                    <textarea id="co_content" name="co_content" class="form-control co_content" required="required" placeholder="回复内容"></textarea>
                                                    <input class="pull-left co_email" type="email" name="co_email" placeholder="请输入接收回复的邮箱" required="required" value="{{session('user.email') ?? ''}}"/>
                                                    <button type="submit" class="btn btn-success child_co_reply" data-pid="{{$childComment->pid ?? ''}}" data-aid="{{$childComment->article_id ?? ''}}" data-rid="{{$childComment->user_id ?? ''}}">回复</button>
                                                    <button type="submit" class="btn btn-success child_co_cancel">取消</button>
                                                </div>
                                            </div>
                                        @endforeach
                                    @endif
                                </div>


                            @endforeach
                            @else
                        <h6 style="text-align: center">暂时没有评论,快来评论吧..</h6>
                        @endif
                    </div>
                </div>

            </div>
        </div>
    @endsection
    <!-- JS -->
    @endsection
    @push('scripts')
        <script>
            var user_id = "{{session('user.id')}}";
            var user_name = "{{session('user.name')}}";
        </script>
        <script src="{{asset('js/home/comment.js').'?ver='.RELEASE_VERSION}}"></script>
        <script src="{{asset('js/jqueryTpfd/js/postbird-img-glass.js').'?ver='.RELEASE_VERSION}}"></script>
        <script>
            PostbirdImgGlass.init({
                domSelector:".hx_article_images img",
                animation:true
            });
        </script>

    @endpush